const API_CONSTANTS = {
    GET_BOOKS: Symbol('GET_BOOKS'),
    GET_BOOKS_SUCCESS: Symbol('GET_BOOKS_SUCCESS'),
    GET_BOOKS_FAIL: Symbol('GET_BOOKS_FAIL'),
    GET_BOOK: Symbol('GET_BOOK'),
    GET_BOOK_SUCCESS: Symbol('GET_BOOK_SUCCESS'),
    GET_BOOK_FAIL: Symbol('GET_BOOK_FAIL'),
    GET_CATEGORIES: Symbol('GET_CATEGORIES'),
    GET_CATEGORIES_SUCCESS: Symbol('GET_CATEGORIES_SUCCESS'),
    GET_CATEGORIES_FAIL: Symbol('GET_CATEGORIES_FAIL'),
    GET_CATEGORY: Symbol('GET_CATEGORY'),
    GET_CATEGORY_SUCCESS: Symbol('GET_CATEGORY_SUCCESS'),
    GET_CATEGORY_FAIL: Symbol('GET_CATEGORY_FAIL'),
    GET_AUTHORS: Symbol('GET_AUTHORS'),
    GET_AUTHORS_SUCCESS: Symbol('GET_AUTHORS_SUCCESS'),
    GET_AUTHORS_FAIL: Symbol('GET_AUTHORS_FAIL'),
    GET_AUTHOR: Symbol('GET_AUTHOR'),
    GET_AUTHOR_SUCCESS: Symbol('GET_AUTHOR_SUCCESS'),
    GET_AUTHOR_FAIL: Symbol('GET_AUTHOR_FAIL'),
    SAVE: Symbol('SAVE'),
    SAVE_SUCCESS: Symbol('SAVE'),
    SAVE_FAIL: Symbol('SAVE')
}

export default API_CONSTANTS;