const API_CONSTANTS = {
    GET_PRODUCTS: Symbol('GET_PRODUCTS'),
    GET_PRODUCTS_SUCCESS: Symbol('GET_PRODUCTS_SUCCESS'),
    GET_PRODUCTS_FAIL: Symbol('GET_PRODUCTS_FAIL'),
    GET_BOOK: Symbol('GET_BOOK'),
    GET_BOOK_SUCCESS: Symbol('GET_BOOK_SUCCESS'),
    GET_BOOK_FAIL: Symbol('GET_BOOk_FAIL')
}

export default API_CONSTANTS;