const API_CONSTANTS = {
    GET_PRODUCTS: Symbol('GET_PRODUCTS'),
    GET_PRODUCTS_SUCCESS: Symbol('GET_PRODUCTS_SUCCESS'),
    GET_PRODUCTS_FAIL: Symbol('GET_PRODUCTS_FAIL')
}

export default API_CONSTANTS;